"""updated_session_table

Revision ID: 8c5daa99a964
Revises: c23dd6da46a0
Create Date: 2025-07-20 20:49:45.899986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c5daa99a964'
down_revision: Union[str, None] = 'c23dd6da46a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('sessions', sa.Column('summary_context', sa.String(length=120), nullable=False))
    op.add_column('sessions', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.drop_index('ix_sessions_name', table_name='sessions')
    op.drop_index('ix_sessions_summary', table_name='sessions')
    op.create_index(op.f('ix_sessions_summary_context'), 'sessions', ['summary_context'], unique=False)
    op.create_index(op.f('ix_sessions_title'), 'sessions', ['title'], unique=False)
    op.drop_column('sessions', 'summary')
    op.drop_column('sessions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('sessions', sa.Column('summary', mysql.VARCHAR(length=120), nullable=False))
    op.drop_index(op.f('ix_sessions_title'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_summary_context'), table_name='sessions')
    op.create_index('ix_sessions_summary', 'sessions', ['summary'], unique=False)
    op.create_index('ix_sessions_name', 'sessions', ['name'], unique=False)
    op.drop_column('sessions', 'extra_metadata')
    op.drop_column('sessions', 'summary_context')
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
